In [ ]:
import numpy as np

# The Basics

In [3]:
# 0-D array
arr0 = np.array(1)
print("Number of dimentions: ", arr0.ndim)
print("Array: ", arr0)


Number of dimentions:  0
Array:  1


In [4]:
# 1-D array
arr1 = np.array([1,2,3])
print("Number of dimentions: ", arr1.ndim)
print("Array: ", arr1)

Number of dimentions:  1
Array:  [1 2 3]


In [5]:
# 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("Number of dimentions: ", arr2.ndim)
print("Array: ", arr2)

Number of dimentions:  2
Array:  [[1 2 3]
 [4 5 6]]


In [6]:
# 3-D array

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Number of dimentions: ", arr3.ndim)
print("Array: \n", arr3)

Number of dimentions:  3
Array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Access Array Elements

In [7]:
# get the first element of this array

arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [8]:
# get an element from a 2-D array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [9]:
# get an element from a 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('last element on 1st row and 2nd column: ', arr[0, 1, 2])

last element on 1st row and 2nd column:  6


In [10]:
# Negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Slicing arrays

In [11]:
# get a range of elements from an array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [12]:
# get a range of elements starting from the index 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [13]:
# get a range of elements ending at the index 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [14]:
# Negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [15]:
# get a range of elements with a step
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [16]:
# get each two elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [17]:
# get the last two elements from second dimension
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, -2:])

[ 9 10]


In [18]:
# get the second elements from the first two rows
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr[0:2, 2])

[3 8]


In [19]:
# get the second and third elements from the first two rows
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
# Everything from (including) the second item to (not including) the fifth item.
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


# Data Types in Python
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


In [21]:
# get the data type of an array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [22]:
# get the data type of an array with strings
arr = np.array(["apple", "banana", "cherry"])
print(arr.dtype)

<U6


In [23]:
# generating an array with specified data type
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [24]:
# generating an array with a defined data type
arr = np.array([1, 2, 3, 4], dtype='i2')
print(arr)
print(arr.dtype)

[1 2 3 4]
int16


In [25]:
# generating a new array by changing the data type of an existing array
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# The Difference Between Copy and View

In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [28]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Shape of an Array

In [29]:
# show the shape of an array with 2 rows and 4 columns
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [30]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

In [31]:
# reshape from 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# reshape from 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [40]:
# the reshape is a view of the original array, so changing the values of the reshaped 
# array will change the original array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
newarr[0, 0] = 99
print(arr)

[99  2  3  4  5  6  7  8]


In [34]:
# adding -1 to the reshape method means that this dimension should be calculated 
# based on the length of the array and remaining dimensions.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Iterating Arrays

In [43]:
# iterating 1-D array
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [45]:
# iterating 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [48]:
# iterating 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [49]:
# iterating 3-D array using nditer()
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays

In [61]:
# concatenate two 1-D arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [57]:
# Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [62]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [64]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Numpy arrays

In [71]:
# split the array into three equal arrays using only one variable to save the split arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [73]:
# split the array into three equal arrays using three variables to save the split arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr1, newarr2, newarr3 = np.array_split(arr, 3)

print(newarr1)
print(newarr2)
print(newarr3)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr[0])

[[1 2 3]
 [4 5 6]]


In [78]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr[0])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


# Searching Arrays

In [80]:
# searching how many times a value occurs in an array
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [82]:
# searching how many odd numbers are in the array
arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)


In [83]:
# Find the indexes where the value 7 should be inserted
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [84]:
# multiple values can be inserted and the return value will be an array of indexes
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays

In [ ]:
# sort an array
arr = np.array([3, 2, 0, 1])

newarr = np.sort(arr)

print(newarr) 

[0 1 2 3]


In [90]:
# sort an array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [92]:
# sort a boolean array
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [93]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

In [ ]:
#Create an array from the elements on index 0 and 2
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [95]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
